name: ecr | frontend

on: push

jobs:
  build_and_push:
    name: "Build frontend image from git tag"
    environment: terraform-aws-ecs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.git_tag }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: "Build Frontend Docker Container"
        env:
          SOURCE_TAG: ${{ github.event.inputs.git_tag }}
          FRONTEND_IMAGE_URI: ${{ secrets.FRONTEND_IMAGE_URI }}

        run: |

          FRONTEND_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-2.amazonaws.com/frontend

          docker build \
            --build-arg SOURCE_TAG=$SOURCE_TAG \
            -t $FRONTEND_IMAGE_URI:$SOURCE_TAG \
            -f nginx/ecs/Dockerfile \
            .

          docker push $FRONTEND_IMAGE_URI:$SOURCE_TAG
